image: hashicorp/terraform

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - terraform init
              - terraform validate
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3
  branches:
    master:
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3
        - step:
            name: Build Infra
            deployment: Production            
            script:
              - cd terraform
              - terraform init
              - terraform plan
              - terraform apply -auto-approve


