name: 'Build and Deploy'
on:
  push:
    paths:     
     - 'hugo/**'
     - 'pycode/**'
     - '!terraform/**'
jobs:
  build_deploy:
    uses: qgriffith/about_me/.github/workflows/build-deploy-callable-wf.yml@master
    with:
      HUGO_VERSION: '0.88.1'
    secrets:
      PELLY_USER: ${{ secrets.PELLY_USER }}
      PELLY_PASS: ${{ secrets.PELLY_PASS }}
      STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
      STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
      STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}