name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      name: Checkout
    - uses: ./.github/workflows/build-deploy-callable-wf
      name: Test