name: build-page
on: [push]
jobs:
   run-python:
     runs-on: ubuntu-latest
     env:
      HUGO_VERSION: '0.88.1'
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
         with:
            python-version: '3.x'
            architecture: 'x64'
       - run: pip install -r pycode/requirements.txt
       - shell: bash
         env:
            PELLY_USER: '${{ secrets.PELLY_USER }}'
            PELLY_PASS: '${{ secrets.PELLY_PASS }}'
         run: | 
           cd pycode/ && python3 fitness_puller.py
       - run: sudo apt-get update -y && sudo apt-get install wget &&  sudo apt-get install git
       - run: wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
       - run: sudo dpkg -i hugo*.deb
       - shell: bash
         env: 
           AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
           AWS__SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
         run: |
           cd hugo/main && hugo -v && hugo deploy && cd ../resume && hugo -v && hugo deploy


